### ISSUE TITLE
Tfs SIGSEGV with Dispatcher::shutdown()

### ISSUE THREAD

**Issue by HeavenIsLost** [otland/forgottenserver#2027]
This is the bt command result in gdb
```
#0  0x0000000000000045 in ?? ()
#1  0x000000000068f547 in Dispatcher::threadMain (this=0x93a160 <g_dispatcher>)
    at /home/distro/src/tasks.cpp:54
#2  0x00007863654efc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007863657c070a in start_thread (arg=0x786363c6d700)
    at pthread_create.c:333
#4  0x0000786364c5582d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
https://github.com/otland/forgottenserver/blob/master/src/tasks.cpp#L54
so it crashed(SIGSEGV) on `delete task;`

Now the task which has been executed:

Frame 1 command "print task->func":

```
 $6 = {<std::_Maybe_unary_or_binary_function<void>> = {<No data fields>}, <std::_Function_base> = {static _M_max_size = 16, static _M_max_align = 8,
    _M_functor = {_M_unused = {_M_object = 0x93a160 <g_dispatcher>,
        _M_const_object = 0x93a160 <g_dispatcher>,
        _M_function_pointer = 0x93a160 <g_dispatcher>,
        _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class * const)) 0x93a160 <g_dispatcher>},
      _M_pod_data = "`\241\223", '\000' <repeats 12 times>},
    _M_manager = 0x68f350 <std::_Function_base::_Base_manager<Dispatcher::shutdown()::<lambda()> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation)>},
  _M_invoker = 0x68f390 <std::_Function_handler<void(), Dispatcher::shutdown()::<lambda()> >::_M_invoke(const std::_Any_data &)>}
```
Which is:
```
void Dispatcher::shutdown()
{
	Task* task = createTask([this]() {
		setState(THREAD_STATE_TERMINATED);
		taskSignal.notify_one();
	});

	std::lock_guard<std::mutex> lockGuard(taskLock);
	taskList.push_back(task);

	taskSignal.notify_one();
}
```
To be more exact:

```
	Task* task = createTask([this]() {
		setState(THREAD_STATE_TERMINATED);
		taskSignal.notify_one();
	});
```

I got now clue how it happened and its the first time i have a crash like this.

@marksamman  @djarek

**Comment by djarek** [comment]
@HeavenIsLost 
Either heap corruption or the crash occurred in an another thread. If you encounter this issue again please make sure you take a backtrace from all threads and/or generate a core file for further examination. I'm closing this issue for now. Feel free to reopen it or create a new one if needed.
