### ISSUE TITLE
Logout Depotlocker container crash

### ISSUE THREAD

**Issue by Znote** [otland/forgottenserver#3450]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Go to your depot
2. Open it, place an item inside
4. Logout
5. Try to Login again
5. Crash 

### Expected behaviour
Nothing, no crash. 

### Actual behaviour
```gdb
#0  0x00007ffff0e103f0 in ?? ()
No symbol table info available.
#1  0x00005555555ebdb8 in Container::~Container (this=<optimized out>, __vtt_parm=<optimized out>, this=<optimized out>, __vtt_parm=<optimized out>) at /home/ubuntu/tfs/github/src/container.cpp:63
        item = 0x7ffff0e13900
        __for_range = std::deque with 2 elements = {0x7ffff0e13900, 0x7ffff05e0c50}
        __for_begin = 0x7ffff0e13900
        __for_end = 0x7ffff05e0c50
        item = <optimized out>
        __for_range = <optimized out>
        __for_begin = <optimized out>
        __for_end = <optimized out>
        item = <optimized out>
        __for_range = <optimized out>
        __for_begin = <optimized out>
        __for_end = <optimized out>
#2  0x0000555555614417 in DepotLocker::~DepotLocker (this=<optimized out>, this=<optimized out>) at /home/ubuntu/tfs/github/src/depotlocker.h:28
No locals.
#3  0x000055555561444c in DepotLocker::~DepotLocker (this=<optimized out>, this=<optimized out>) at /home/ubuntu/tfs/github/src/depotlocker.h:28
No locals.
#4  0x000055555582c3fd in std::_Sp_counted_ptr<DepotLocker*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x7ffff0d06b90) at /usr/include/c++/9/bits/shared_ptr_base.h:377
No locals.
#5  0x000055555559ce22 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7ffff0d06b90) at /usr/include/c++/9/bits/shared_ptr_base.h:155
No locals.
#6  0x000055555559c973 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>, this=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:730
No locals.
#7  0x000055555582a54a in std::__shared_ptr<DepotLocker, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>, this=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1169
No locals.
#8  0x000055555582a564 in std::shared_ptr<DepotLocker>::~shared_ptr (this=<optimized out>, this=<optimized out>) at /usr/include/c++/9/bits/shared_ptr.h:103
No locals.
#9  0x000055555582a582 in std::pair<unsigned int const, std::shared_ptr<DepotLocker> >::~pair (this=<optimized out>, this=<optimized out>) at /usr/include/c++/9/bits/stl_pair.h:208
No locals.
#10 0x000055555582a5a0 in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > >::destroy<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > (this=0x7ffff0e0f418, __p=0x555555ab3a70) at /usr/include/c++/9/ext/new_allocator.h:153
No locals.
#11 0x00005555558290a3 in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > > >::destroy<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > (__a=..., __p=0x555555ab3a70) at /usr/include/c++/9/bits/alloc_traits.h:497
No locals.
#12 0x0000555555827003 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::shared_ptr<DepotLocker> >, std::_Select1st<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > >::_M_destroy_node (this=0x7ffff0e0f418, __p=0x555555ab3a50) at /usr/include/c++/9/bits/stl_tree.h:642
No locals.
#13 0x0000555555823eab in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::shared_ptr<DepotLocker> >, std::_Select1st<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > >::_M_drop_node (
    this=0x7ffff0e0f418, __p=0x555555ab3a50) at /usr/include/c++/9/bits/stl_tree.h:650
No locals.
#14 0x0000555555820f9c in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::shared_ptr<DepotLocker> >, std::_Select1st<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > >::_M_erase (
    this=0x7ffff0e0f418, __x=0x555555ab3a50) at /usr/include/c++/9/bits/stl_tree.h:1915
        __y = 0x0
#15 0x000055555581eb38 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, std::shared_ptr<DepotLocker> >, std::_Select1st<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > >::~_Rb_tree (
    this=<optimized out>, this=<optimized out>) at /usr/include/c++/9/bits/stl_tree.h:995
No locals.
#16 0x000055555580a310 in std::map<unsigned int, std::shared_ptr<DepotLocker>, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::shared_ptr<DepotLocker> > > >::~map (this=<optimized out>, this=<optimized out>) at /usr/include/c++/9/bits/stl_map.h:300
No locals.
#17 0x000055555580be7c in Player::~Player (this=<optimized out>, this=<optimized out>) at /home/ubuntu/tfs/github/src/player.cpp:59
        item = <optimized out>
        __for_range = <optimized out>
        __for_begin = <optimized out>
        __for_end = <optimized out>
        it = <optimized out>
        __for_range = <optimized out>
        __for_begin = <optimized out>
        __for_end = <optimized out>
#18 0x000055555580bf32 in Player::~Player (this=<optimized out>, this=<optimized out>) at /home/ubuntu/tfs/github/src/player.cpp:79
No locals.
#19 0x00005555555f51f6 in Creature::decrementReferenceCounter (this=0x7ffff0e0f030) at /home/ubuntu/tfs/github/src/creature.h:466
No locals.
#20 0x0000555555638f1b in Game::cleanup (this=0x555555a7b760 <g_game>) at /home/ubuntu/tfs/github/src/game.cpp:4574
        creature = 0x7ffff0e0f030
        __for_range = std::vector of length 1, capacity 16 = {0x7ffff0e0f030}
        __for_begin = 0x7ffff0e0f030
        __for_end = 0x7ffff12cf770
#21 0x000055555563441e in Game::checkCreatures (this=0x555555a7b760 <g_game>, index=8) at /home/ubuntu/tfs/github/src/game.cpp:3744
        checkCreatureList = std::__cxx11::list = {[0] = 0x7ffff0652310, [1] = 0x7ffff01aa890, [2] = 0x7ffff01a8bb0}
        it = 0x3
        end = 0x3
#22 0x0000555555663169 in std::__invoke_impl<void, void (Game::*&)(unsigned long), Game*&, unsigned long&> (__f=@0x7ffff0e0ed40: (void (Game::*)(Game * const, unsigned long)) 0x5555556341e4 <Game::checkCreatures(unsigned long)>, __t=@0x7ffff0e0ed58: 0x555555a7b760 <g_game>) at /usr/include/c++/9/bits/invoke.h:73
No locals.
#23 0x000055555565e901 in std::__invoke<void (Game::*&)(unsigned long), Game*&, unsigned long&> (__fn=@0x7ffff0e0ed40: (void (Game::*)(Game * const, unsigned long)) 0x5555556341e4 <Game::checkCreatures(unsigned long)>) at /usr/include/c++/9/bits/invoke.h:95
No locals.
#24 0x000055555565895a in std::_Bind<void (Game::*(Game*, unsigned long))(unsigned long)>::__call<void, , 0ul, 1ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul>) (this=0x7ffff0e0ed40, __args=...) at /usr/include/c++/9/functional:400
No locals.
#25 0x0000555555650b0b in std::_Bind<void (Game::*(Game*, unsigned long))(unsigned long)>::operator()<, void>() (this=0x7ffff0e0ed40) at /usr/include/c++/9/functional:484
--Type <RET> for more, q to quit, c to continue without paging--
No locals.
#26 0x00005555556493f3 in std::_Function_handler<void (), std::_Bind<void (Game::*(Game*, unsigned long))(unsigned long)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/9/bits/std_function.h:300
No locals.
#27 0x00005555558acd44 in std::function<void ()>::operator()() const (this=0x555555ab1b00) at /usr/include/c++/9/bits/std_function.h:688
No locals.
#28 0x00005555558ac7b6 in Task::operator() (this=0x555555ab1af0) at /home/ubuntu/tfs/github/src/tasks.h:41
No locals.
#29 0x00005555558aca22 in Dispatcher::threadMain (this=0x555555a7b640 <g_dispatcher>) at /home/ubuntu/tfs/github/src/tasks.cpp:57
        task = 0x555555ab1af0
        __for_range = std::vector of length 1, capacity 4 = {0x555555ab1af0}
        __for_begin = 0x555555ab1af0
        __for_end = 0x555555ab2ba0
        tmpTaskList = std::vector of length 1, capacity 4 = {0x555555ab1af0}
        taskLockUnique = {_M_device = 0x555555a7b650 <g_dispatcher+16>, _M_owns = false}
#30 0x00005555557fd5dc in std::__invoke_impl<void, void (Dispatcher::*)(), Dispatcher*> (__f=@0x555555aab370: (void (Dispatcher::*)(Dispatcher * const)) 0x5555558ac8e0 <Dispatcher::threadMain()>, __t=@0x555555aab368: 0x555555a7b640 <g_dispatcher>) at /usr/include/c++/9/bits/invoke.h:73
No locals.
#31 0x00005555557fd31f in std::__invoke<void (Dispatcher::*)(), Dispatcher*> (__fn=@0x555555aab370: (void (Dispatcher::*)(Dispatcher * const)) 0x5555558ac8e0 <Dispatcher::threadMain()>) at /usr/include/c++/9/bits/invoke.h:95
No locals.
#32 0x00005555557fceaf in std::thread::_Invoker<std::tuple<void (Dispatcher::*)(), Dispatcher*> >::_M_invoke<0ul, 1ul> (this=0x555555aab368) at /usr/include/c++/9/thread:244
No locals.
#33 0x00005555557fc8c8 in std::thread::_Invoker<std::tuple<void (Dispatcher::*)(), Dispatcher*> >::operator() (this=0x555555aab368) at /usr/include/c++/9/thread:251
No locals.
#34 0x00005555557fc014 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (Dispatcher::*)(), Dispatcher*> > >::_M_run (this=0x555555aab360) at /usr/include/c++/9/thread:195
No locals.
#35 0x00007ffff7e93d84 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#36 0x00007ffff7fa7609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737320060672, 7971852446868416743, 140737488347294, 140737488347295, 140737488347296, 140737320058752, -7971830387944216345, -7971834901734774553}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#37 0x00007ffff7cd2293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### Environment
Ubuntu 20.04, GCC 9.3.0

### Reproduction environment
Crash appears to be OS specific to Linux (tested on Ubuntu 20.04 so far, @nekiro tested on Windows and seems to work there).

**Comment by Znote** [comment]
Target commit that caused this:
```
commit dd934dd8e5b68e842714e400f182527a768ecab8
Author: nekiro <nekiroboy@gmail.com>
Date:   Fri Apr 23 21:31:56 2021 +0200

    Use shared_ptr for depot locker and depot chests (#3423)
```
